server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/test-user/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/test-order/**
          filters:
            - StripPrefix=1
        - id: demo-api
          uri: lb://demo-api
          predicates:
            - Path=/test-api/**
          filters:
            - StripPrefix=1
        - id: demo-service
          uri: lb://demo-service
          predicates:
            - Path=/test-service/**
          filters:
            - StripPrefix=1
      default-filters:
        - PreserveHostHeader

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    # 开启健康检查
    healthcheck:
      enabled: true
  # 使用ip替代实例
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"