server:
  port: 9001

spring:
  application:
    name: eurake
  messages:
    encoding: utf-8

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #不开启注册
    fetch-registry: false

