spring:
  messages:
    encoding: utf-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS