spring:
  messages:
    encoding: utf-8
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 50
        max-wait: 2000ms
        min-idle: 0

eureka:
 client:
  service-url:
   defaultZone: http://localhost:9001/eureka/